### ISSUE TITLE
 I encountered a problem when I integrated the project

### ISSUE THREAD

**Issue by 160nothelp** [django-wiki/django-wiki#1041]
migrate:
emmmmmmmmmmmmmm

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/opt/ops-env/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/ops-env/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/ops-env/lib64/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/ops-env/lib64/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/opt/ops-env/lib64/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/ops-env/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 85, in handle
    executor.loader.check_consistent_history(connection)
  File "/opt/ops-env/lib64/python3.6/site-packages/django/db/migrations/loader.py", line 297, in check_consistent_history
    connection.alias,
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration wiki.0001_initial is applied before its dependency sites.0001_initial on database 'default'.

**Comment by benjaoming** [comment]
Make sure you have `sites` enabled: https://django-wiki.readthedocs.io/en/master/installation.html#configuration

**Comment by 160nothelp** [comment]
我当然按照文档做的
