### ISSUE TITLE
Error on foreign key constraints when runing migrate

### ISSUE THREAD

**Issue by paulgreg** [django-wiki/django-wiki#1147]
When running `python manage.py migrate` on an empty database, I’ve got foreign key constraints errors :

```
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_nyt, repaircafeapp, sessions, sites, thumbnail, wiki, wiki_attachments, wiki_images, wiki_notifications
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying django_nyt.0001_initial... OK
  Applying django_nyt.0002_notification_settings... OK
  Applying django_nyt.0003_subscription... OK
  Applying django_nyt.0004_notification_subscription... OK
  Applying django_nyt.0005__v_0_9_2... OK
  Applying django_nyt.0006_auto_20141229_1630... OK
  Applying django_nyt.0007_add_modified_and_default_settings... OK
  Applying django_nyt.0008_auto_20161023_1641... OK
  Applying django_nyt.0009_auto_20211009_2254... OK
  Applying repaircafeapp.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying thumbnail.0001_initial... OK
  Applying wiki.0001_initial... OK
  Applying wiki.0002_urlpath_moved_to... OK
  Applying wiki.0003_mptt_upgrade... OK
  Applying wiki.0004_auto_20211103_0834...Traceback (most recent call last):
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1833, "Cannot change column 'articleplugin_ptr_id': used in a foreign key constraint 'wiki_revisionpluginr_plugin_id_c8f4475b_fk_wiki_revi' of table 'repaircafedb.wiki_revisionpluginrevision'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/paulgreg/Projects/software/repair-cafe/django/repaircafesite/manage.py", line 22, in <module>
    main()
  File "/home/paulgreg/Projects/software/repair-cafe/django/repaircafesite/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/migrations/operations/fields.py", line 244, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 608, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 830, in _alter_field
    self.execute(
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/paulgreg/.local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1833, "Cannot change column 'articleplugin_ptr_id': used in a foreign key constraint 'wiki_revisionpluginr_plugin_id_c8f4475b_fk_wiki_revi' of table 'repaircafedb.wiki_revisionpluginrevision'")
```

My migration `repaircafeapp.0001_initial` is creating another table without touching wiki tables.

The problem occurs on wiki 0.7.7 and also on latest version 0.7.8.

Any idea why I’m getting that error ?

**Comment by benjaoming** [comment]
Hi @paulgreg !

Thanks for reporting this. It's been a long time since I used MySQL, but I remember that handling of constraints can involve manual fiddling.

Is you DB already empty? If so, you could try to delete the database and start over. 

I can't reproduce this issue with SQLite.

**Comment by paulgreg** [comment]
Hello,

Yes, I tried to drop every tables from the database and ran again the migration.
But I’m always getting that same error.

I’m using MariaDB [via that docker-compose.yml](https://github.com/paulgreg/repaircafesite/blob/main/docker-compose.yml) for development and native package from debian 11 on server. Both are reporting the same error.

**Comment by benjaoming** [comment]
@paulgreg

I'm not sure what the constraint is doing or if it's present in the database as an old artifact. But dropping the tables should ideally also remove these constraints.

What you could do as a work-around would be to run migrations up until the point where they break, then manually delete the constraint `wiki_revisionpluginr_plugin_id_c8f4475b_fk_wiki_revi`

(haven't tested, but should be something like this, run on appropriate tables until the constraint is gone)

```
ALTER TABLE wiki_revisionplugin
DROP INDEX wiki_revisionpluginr_plugin_id_c8f4475b_fk_wiki_revi;
```

**Comment by paulgreg** [comment]
I tried that but I also had to drop `wiki_reusableplugin__reusableplugin_id_52618a1c_fk_wiki_reus` constraint.

The migration then completes but the foreign key isn’t restored at the end...

**Comment by benjaoming** [comment]
@paulgreg - thanks for trying out stuff!

These migrations have been generated over quite a long period of time, so I'm wondering if the underlying cause can be some different newer ways of generating migrations that ultimately can support MySQL or MariaDB in whatever way that's failing here.

This could way in as a reason to cut out a new release branch and entirely re-do all migrations.

**Comment by paulgreg** [comment]
Thanks for working on that issue :-) 

Indeed, that would be a good idea and a nice solution :-)

**Comment by rcooke** [comment]
This seems to be tickling a known Django problem that will be fixed soon.  Meanwhile, you can work around it by squashing the offending migrations.

If the database is left in a messed up state, install Django-Extensions and use reset_db to erase it so you can start over.

```
# pip install django-extensions 
#./manage.py reset_db 
./manage.py squashmigrations wiki 0004
./manage.py migrate wiki
./manage.py migrate
```

This completes without errors on a fresh install under Django 3.2 and Python 3.9 (on PythonAnywhere.com)

**Comment by paulgreg** [comment]
Thank you. I will try that.
