### ISSUE TITLE
cannot import name 'Group' from 'channels'

### ISSUE THREAD

**Issue by charlesMayConequip** [django-wiki/django-wiki#1193]
I just implemented channels into my main django project and realized afterwards that the wiki is no longer working.  It seems to be within the notification system within this project.  I was curious if there was an easy solution such as turning off notifications in the settings or if there was any other alternative like this that I was unaware of.  Any help is appreciated, the error I'm getting within django is listed below.  Thanks!
```
Internal Server Error: /app/wiki/_edit/
Traceback (most recent call last):
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\asgiref\sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\asgiref\sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Users\charlesmay-pc\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
  File "C:\Users\charlesmay-pc\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\asgiref\sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\wiki\decorators.py", line 171, in wrapper
    return func(request, article, *args, **kwargs)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\wiki\views\article.py", line 256, in dispatch
    return super().dispatch(request, article, *args, **kwargs)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\wiki\views\mixins.py", line 34, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\wiki\views\article.py", line 365, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\django\views\generic\edit.py", line 144, in post
    return self.form_valid(form)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\wiki\views\article.py", line 377, in form_valid
    self.article.add_revision(revision)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\wiki\models\article.py", line 177, in add_revision
    new_revision.save()
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\django\db\models\base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\django\db\models\base.py", line 791, in save_base
    post_save.send(
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\django\dispatch\dispatcher.py", line 170, in send
    return [
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\django\dispatch\dispatcher.py", line 171, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\wiki\decorators.py", line 197, in wrapper
    return signal_handler(*args, **kwargs)
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\wiki\plugins\notifications\models.py", line 53, in post_article_revision_save      
    notify(
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\django_nyt\utils.py", line 55, in notify
    from django_nyt import subscribers
  File "C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\django_nyt\subscribers.py", line 3, in <module>
    from channels import Group
ImportError: cannot import name 'Group' from 'channels' (C:\Users\Charlie May\Desktop\CID\myenv\lib\site-packages\channels\__init__.py)
HTTP POST /app/wiki/_edit/ 500 [0.11, 127.0.0.1:60303]
```

**Comment by benjaoming** [comment]
`django_nyt` is probably not compatible with your version of django-channels. The integration is very old. If you set `settings.ENABLE_CHANNELS = False`, you can get rid of this.

**Comment by charlesMayConequip** [comment]
I used '''NYT_ENABLE_CHANNELS= False''' and I'm still getting the same error on edit.  Is there a wiki setting to turn off notifications?

**Comment by benjaoming** [comment]
Oh wow, this was implemented very un-intuitively - you need to do set `NYT_CHANNELS_DISABLE = True`

See: https://github.com/django-wiki/django-nyt/blob/24c2e60fa7fa1ec669cb56be17731ab848539815/django_nyt/settings.py#L61

**Comment by charlesMayConequip** [comment]
Back up and running!  Thanks for the help!
