### ISSUE TITLE
[Bug]: Separate documentation environment from build environment

### ISSUE THREAD

**Issue by Dev-Mehta** [django-wiki/django-wiki#1367]
### Discussed in https://github.com/django-wiki/django-wiki/discussions/1366

<div type='discussions-op-text'>

<sup>Originally posted by **Dev-Mehta** August  7, 2024</sup>
### Describe the bug

I have contributed previously to this repo in #1203. I was wondering if I could contribute in a similar fashion with other models and wanted to test if affects performance or any querying issues with django-debug-toolbar like the ones discussed in #1365 

I read the developer guide at https://django-wiki.readthedocs.io/en/latest/development/index.html but when I run the command `hatch env create` it throws off error such as this.

```
raceback (most recent call last):
    File "C:\Users\Admin\AppData\Local\hatch\env\virtual\wiki\U-kTVpY0\wiki\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 167, in prepare_metadata_for_build_editable 
      hook = backend.prepare_metadata_for_build_editable
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'   

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\Admin\AppData\Local\hatch\env\virtual\wiki\U-kTVpY0\wiki\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\Admin\AppData\Local\hatch\env\virtual\wiki\U-kTVpY0\wiki\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Admin\AppData\Local\hatch\env\virtual\wiki\U-kTVpY0\wiki\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 176, in prepare_metadata_for_build_editable 
      whl_basename = build_hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-8wc2gdoc\overlay\Lib\site-packages\hatchling\build.py", line 83, in build_editable
      return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-8wc2gdoc\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 147, in build
      build_hook.initialize(version, build_data)
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-8wc2gdoc\overlay\Lib\site-packages\hatch_build_scripts\plugin.py", line 51, in initialize
      run(cmd, cwd=str(work_dir), check=True, shell=True)  # noqa: S602
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Admin\AppData\Local\hatch\env\virtual\.pythons\3.12\python\Lib\subprocess.py", line 571, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '[[ -z $READTHEDOCS_VIRTUALENV_PATH ]] && pysassc --style compressed src/wiki/static/wiki/bootstrap/scss/wiki/wiki-bootstrap.scss src/wiki/static/wiki/bootstrap/css/wiki-bootstrap.min.css || true' returned non-zero exit status 1.
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I found the github issues and [stackoverflow answer](https://stackoverflow.com/a/73332363) related to this error. But it doesn't seem to work. I tried placing the given solution code block to allow usage of direct references in metadata, at 2-3 different places. Could anybody help me figure out what am I doing wrong, or is it an issue with a broken package?

The said code block

```
[tool.hatch.metadata]
allow-direct-references = true
```

pyproject.toml file

```
[build-system]
requires = ["hatchling", "hatch-build-scripts"]
build-backend = "hatchling.build"

[project]
name = "wiki"
description = "A wiki system written for the Django framework."
readme = "README.rst"
requires-python = ">=3.9"
license = "GPL-3.0"
keywords = ["django", "wiki", "markdown"]
authors = [
    { name = "Benjamin Bach", email = "benjamin@overtag.dk" },
]
maintainers = [
    { name = "Oscar Cortez", email = "om.cortez.2010@gmail.com" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.1",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.0",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Wiki",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
dependencies = [
    # Django version support is added one minor release at a time
    "Django>=3.2,<5.1",
    # bleach has been pretty stable, hence the loose pin
    "bleach[css]>=6,<7",
    # Pillow is used very little and has never broken
    "Pillow",
    # django-nyt is maintained by django-wiki maintainers, so we can
    # control breakage and pinning ourselves
    "django-nyt>=1.4,<1.5",
    # django-mptt has had several breaking changes
    "django-mptt>=0.13,<0.17",
    # django-sekizai is basically only releasing every time
    # it needs to restore support for a new Django/Python version
    "django-sekizai>=0.10",
    # sorl-thumbnail is maintained by jazzband so it might be
    # very stable but it might also suddenly invite breaking changes
    "sorl-thumbnail>=12.8,<13",
    # django-wiki's integration with Markdown is really detailed,
    # several extensions have imported internal APIs, so be very
    # careful here.
    "Markdown>=3.4,<3.7",
    # Set of extensions for Python Markdown.
    "pymdown-extensions>=10.5,<10.6",
]
dynamic = ["version"]

[project.optional-dependencies]
docs = [
    "sphinx>=6,<8",
    "sphinx_rtd_theme==2.0.0",
]
[tool.hatch.metadata]
allow-direct-references = true
[project.urls]
Homepage = "http://www.django-wiki.org"
Documentation = "https://django-wiki.readthedocs.io/en/latest/"
Tracker = "https://github.com/django-wiki/django-wiki/issues"
Source = "https://github.com/django-wiki/django-wiki"

[[tool.hatch.build.hooks.build-scripts.scripts]]
out_dir = "src/wiki/static/wiki/bootstrap/css/"
commands = [
    "[[ -z $READTHEDOCS_VIRTUALENV_PATH ]] && pysassc --style compressed src/wiki/static/wiki/bootstrap/scss/wiki/wiki-bootstrap.scss src/wiki/static/wiki/bootstrap/css/wiki-bootstrap.min.css || true",
]
artifacts = [
    "wiki-bootstrap.min.css",
]
clean_artifacts = true
clean_out_dir = true

[tool.hatch.publish.index]
disable = true

[tool.hatch.version]
path = "src/wiki/__about__.py"

[tool.hatch.build.targets.sdist]
include = [
    "COPYING",
    "README.rst",
    "/src",
]
exclude = [
    "src/wiki/locale/en/LC_MESSAGES/django.mo",
]

[tool.hatch.envs.default]
dependencies = [
    "ruff==0.1.3",
    "ddt==1.6.0",
    "django-functest>=1.2,<1.6",
    "pre-commit==3.5.0",
    "pytest-cov",
    "pytest-django",
    "pytest-pythonpath",
    "pytest>=6.2.5,<7.3",
    "hatch-build-scripts==0.0.4",
]

[tool.hatch.envs.default.scripts]
lint = [
    "ruff check src/wiki tests/ {args}",
    "pre-commit install -f --install-hooks",
    "pre-commit run --all-files --show-diff-on-failure",
]
format = "ruff format src/wiki tests/ {args}"
clean = [
    "hatch run clean-build",
    "hatch run clean-pyc",
    "rm -fr htmlcov/",
]
clean-build = [
    "rm -fr build",
    "rm -fr dist",
    "rm -fr .eggs",
    "find . -name '*.egg-info' -exec rm -fr {{}} +",
    "find . -name '*.egg' -exec rm -f {{}} +",
]
clean-pyc = [
    "find . -name '*.pyc' -exec rm -f {{}} +",
    "find . -name '*.pyo' -exec rm -f {{}} +",
    "find . -name '*~' -exec rm -f {{}} +",
    "find . -name '__pycache__' -exec rm -fr {{}} +",
]
test = "pytest {args}"

[tool.hatch.envs.test.overrides]
matrix.django.dependencies = [
    { value = "django~={matrix:django}" },
]

[tool.hatch.envs.test]
matrix-name-format = "dj{value}"

[tool.hatch.envs.test.scripts]
all = [
    "sh -c 'testproject/manage.py makemigrations --check'",
    "pytest tests/ --cov=wiki {args}",
]

[[tool.hatch.envs.test.matrix]]
python = ["3.9", "3.10"]
django = ["3.2", "4.0"]

[[tool.hatch.envs.test.matrix]]
python = ["3.9", "3.10", "3.11"]
django = ["4.1", "4.2"]

[[tool.hatch.envs.test.matrix]]
python = ["3.10", "3.11", "3.12"]
django = ["5.0"]

[tool.hatch.envs.transifex]
dependencies = []

[tool.hatch.envs.transifex.scripts]
push = [
    "touch ~/.transifexrc",
    # Recipe: https://github.com/transifex/cli#running-from-docker-beta
    "docker run --rm -i -t -v `pwd`:/app -v ~/.transifexrc:/.transifexrc -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt transifex/txcli --root-config /.transifexrc push -s",
]
pull = [
    "touch ~/.transifexrc",
    # Recipe: https://github.com/transifex/cli#running-from-docker-beta
    "docker run --rm -i -t -v `pwd`:/app -v ~/.transifexrc:/.transifexrc -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt transifex/txcli --root-config /.transifexrc pull -a",
    # This can have permission errors because of Docker
    # In this case, run chown -R USERNAME:USERGROUP src/wiki/locale
    "cd src/wiki && django-admin compilemessages",
]

[tool.hatch.envs.docs]
dependencies = [
    "sphinx>=6,<8",
    "sphinx_rtd_theme==2.0.0",
]

[tool.hatch.envs.docs.scripts]
clean = "rm -rf docs/_build/*"
html = "sphinx-build -c docs -b html -d docs/_build/doctrees docs/ docs/_build/html"
dirhtml = "sphinx-build -c docs -b dirhtml -d docs/_build/doctrees docs/ docs/_build/dirhtml"
singlehtml = "sphinx-build -c docs -b singlehtml -d docs/_build/doctrees docs/ docs/_build/singlehtml"
pickle = "sphinx-build -c docs -b pickle -d docs/_build/doctrees docs/ docs/_build/pickle"
json = "sphinx-build -c docs -b json -d docs/_build/doctrees docs/ docs/_build/json"
htmlhelp = [
    "sphinx-build -c docs -b htmlhelp -d docs/_build/doctrees docs/ docs/_build/htmlhelp",
    "echo 'Build finished; now you can run HTML Help Workshop with the .hhp project file in docs/_build/htmlhelp.'",
]
qthelp = [
    "sphinx-build -c docs -b qthelp -d docs/_build/doctrees docs/ docs/_build/qthelp",
    "echo 'Build finished; now you can run qcollectiongenerator with the .qhcp project file in docs/_build/qthelp, like this:'",
    "echo '# qcollectiongenerator docs/_build/qthelp/django-wiki.qhcp'",
    "echo 'To view the help file:'",
    "echo '# assistant -collectionFile docs/_build/qthelp/django-wiki.qhc'",
]
devhelp = [
    "sphinx-build -c docs -b devhelp -d docs/_build/doctrees docs/ docs/_build/devhelp",
    "echo 'Build finished.'",
    "echo 'To view the help file:'",
    "echo '# mkdir -p $$HOME/.local/share/devhelp/django-wiki'",
    "echo '# ln -s docs/_build/devhelp $$HOME/.local/share/devhelp/django-wiki'",
    "echo '# devhelp'",
]
epub = "sphinx-build -c docs -b epub -d docs/_build/doctrees docs/ docs/_build/epub"
latex = [
    "sphinx-build -c docs -b latex -d docs/_build/doctrees -D latex_paper_size={args} docs/ docs/_build/latext",
    "echo 'Build finished; the LaTeX files are in docs/_build/latex.'",
    "echo 'Run `make` in that directory to run these through (pdf)latex'",
    "echo '(use `make latexpdf` here to do that automatically).'",
]
latexpdf = [
    "sphinx-build -c docs -b latex -d docs/_build/doctrees -D latex_paper_size={args} docs/ docs/_build/latext",
    "echo 'Running LaTeX files through pdflatex...'",
    "make -C docs/_build/latex all-pdf",
    "echo 'pdflatex finished; the PDF files are in docs/_build/latex.'",
]
text = "sphinx-build -c docs -b text -d docs/_build/doctrees  docs/ docs/_build/text"
man = "sphinx-build -c docs -b man -d docs/_build/doctrees  docs/ docs/_build/man"
texinfo = [
    "sphinx-build -c docs -b text -d docs/_build/doctrees  docs/ docs/_build/text",
    "echo 'Build finished. The Texinfo files are in docs/_build/texinfo.'",
    "echo 'Run `make` in that directory to run these through makeinfo'",
    "echo '(use `make info` here to do that automatically).'",
]
info = [
    "sphinx-build -c docs -b texinfo -d docs/_build/doctrees  docs/ docs/_build/texinfo",
    "echo 'Running Texinfo files through makeinfo...'",
    "make -C docs/_build/texinfo info",
    "echo 'makeinfo finished; the Info files are in docs/_build/texinfo.'",
]
gettext = "sphinx-build -c docs -b gettext  docs/_build/locale"
changes = "sphinx-build -c docs -b changes -d docs/_build/doctrees  docs/ docs/_build/changes"
link-check2 = "sphinx-build -c docs -b linkcheck -d docs/_build/doctrees  docs/ docs/_build/linkcheck"
doctest = "sphinx-build -c docs -b doctest -d docs/_build/doctrees  docs/ docs/_build/doctest"
build = [
    "hatch run docs:clean",
    "rm -f docs/wiki*.rst",
    "rm -f docs/modules.rst",
    "sphinx-apidoc -o docs/ src/wiki",
    "hatch run docs:html {args}",
    """
    python -c '
import os, webbrowser, sys
try:
  from urllib import pathname2url
except:
  from urllib.request import pathname2url

  webbrowser.open(\"file://\" + pathname2url(os.path.abspath(\"docs/_build/html/index.html\")))
    '"""
]
link-check = "sphinx-build -b linkcheck ./docs ./docs/_build"

[tool.coverage.run]
disable_warnings = ['no-data-collected']
branch = true
parallel = true
source = [
    "src/",
]
omit = [
    ".DS_Store",
    "*/tests/*",
    "src/wiki/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
    "no cov",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

[tool.ruff]
exclude = ["env", "_build", "CVS", "__pycache__", ".eggs", "*.egg", "*/*migrations", "testproject"]
extend-ignore = ["E203"]
line-length = 79

[tool.ruff.mccabe]
max-complexity = 10

[tool.pytest.ini_options]
django_find_project = false
testpaths = [
    "tests",
]
norecursedirs = [
    "testproject",
    ".svn",
    "_build",
    "tmp*",
    "dist",
    "*.egg-info",
]
DJANGO_SETTINGS_MODULE = "tests.settings"
```

### Steps to reproduce.

1. Try setting up a developer environment with instructions given at https://django-wiki.readthedocs.io/en/latest/development/index.html

### Expected behavior

Setting up developer environment without any errors

### Python Version

3.11.4

### Django Version

5.0.3

### Extra context

_No response_</div>

**Comment by benjaoming** [comment]
This looks related to a recent change where pysassc became part of the build stack (it compiles SCSS sources to CSS) see: #1363

The command will skip it if `READTHEDOCS_VIRTUALENV_PATH` is defined, so you could try to define that environment variable, for instance see if `READTHEDOCS_VIRTUALENV_PATH=1 hatch env create` works?

@oscarmcm you might know better how to support this?

**Comment by Dev-Mehta** [comment]
Let me see if setting `READTHEDOCS_VIRTUALENV_PATH` works

**Comment by Dev-Mehta** [comment]
@benjaoming 

Nope still getting the same error. 

![image](https://github.com/user-attachments/assets/d0395b2a-5af8-48f5-9b90-2fd7072e840f)

**Comment by Dev-Mehta** [comment]
@benjaoming I believe the command declared here at [pyproject.toml](https://github.com/django-wiki/django-wiki/blob/main/pyproject.toml#L84) is a command for unix systems. As I am working on windows this command seems to be breaking the code here.

**Comment by benjaoming** [comment]
@Dev-Mehta ah yes, I see there are two errors in play :facepalm: 

Can you check if adding this to your pyproject.toml fixes the issue? https://github.com/pypa/hatch/issues/1114#issuecomment-2151416879

Regarding Windows - it's true that many Unix shell commands will not run on Windows. I'm not sure what the best solution for this is.. if the fix is easy and doesn't make our solutions worse, then that's fine. But it'll probably have to be Windows-developers that take the lead on this :)

**Comment by Dev-Mehta** [comment]
@benjaoming I have updated my previous comment with what worked for me. Can we create two seperate pyproject.toml files - one for windows based systems and one for unix based?

**Comment by benjaoming** [comment]
Sounds good! I guess we need a new separate environment for documentation builds that don't have a dependency on pysassc. Maybe @oscarmcm has inputs

I don't think maintaining separate pyproject.toml's is the solution.

**Comment by Dev-Mehta** [comment]
@benjaoming @oscarmcm any updates on this issue?

**Comment by benjaoming** [comment]
For now, I'm gonna say that the immediate problem is about the build environment not working on Windows because we're using a command that's only there so the documentation can run without a full build. In short: Support for Read the Docs breaks setting up the Windows development environment.

Depending on some experiments, there might not be any need to actually run/build the project in order to build the documentation. We do this to add [this reference](https://django-wiki.readthedocs.io/en/main/settings.html) to all settings modules.

Let's try to minimize the amount of dependencies necessary to generate the documentation (including API docs for `settings`), and then keep that in a separate `documentation` environment?

**Comment by oscarmcm** [comment]
I see the error, I'll take a look to see how we can improve the build process

**Comment by Dev-Mehta** [comment]
Hey @benjaoming @oscarmcm, I was wondering,

Won't the solution described here, https://github.com/django-wiki/django-wiki/issues/1367#issuecomment-2273357855 Work in both windows and Unix based systems? It already works in my windows environment, you can check if it works in your Unix based environment?🤔

As you were using `pysassc` but the package I mentioned (`pysass`) is a wrapper around that tool. You can look at the comment I mentioned and pysass webpage - https://pypi.org/project/pysass/

**Comment by oscarmcm** [comment]
I think the error is more on the binding of PYSASSC rather than the shell command itself.
