### ISSUE TITLE
Markdown 2.5.2 is broken?

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#365]
Downgrading Markdown to 2.4 fixes the following issue:

    Internal Server Error: /
    Traceback (most recent call last):
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
        resolver_match = resolver.resolve(request.path_info)
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
        for pattern in self.url_patterns:
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
        patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
        self._urlconf_module = import_module(self.urlconf_name)
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
        __import__(name)
      File "/home/user/lalala/lalala/urls.py", line 21, in <module>
        from wiki.urls import get_pattern as get_wiki_pattern
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/wiki/urls.py", line 156, in <module>
        load_wiki_plugins()
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/wiki/core/plugins/loader.py", line 38, in load_wiki_plugins
        load('wiki_plugin', verbose=False, failfast=False)
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/wiki/core/plugins/loader.py", line 35, in load
        get_module(app, modname, verbose, failfast)
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/wiki/core/plugins/loader.py", line 17, in get_module
        module = import_module(module_name)
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
        __import__(name)
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/wiki/plugins/links/wiki_plugin.py", line 13, in <module>
        class LinkPlugin(BasePlugin):
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/wiki/plugins/links/wiki_plugin.py", line 33, in LinkPlugin
        markdown_extensions = [urlize_makeExtension(), WikiPathExtension(wikipath_config)]
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/wiki/plugins/links/mdx/urlize.py", line 100, in makeExtension
        return UrlizeExtension(configs=configs)
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/markdown/extensions/__init__.py", line 36, in __init__
        self.setConfigs(kwargs.pop('configs', {}))
      File "/home/user/.virtualenvs/test/local/lib/python2.7/site-packages/markdown/extensions/__init__.py", line 75, in setConfigs
        for key, value in items:
    TypeError: 'NoneType' object is not iterable

**Comment by benjaoming** [comment]
Same issue in 2.5.1

**Comment by benjaoming** [comment]
Okay this issue is only relevant for 0.0.23 and not in the current master, before and after #367. So closing again..

**Comment by orblivion** [comment]
Yeah, #314 fixes it, #367 just makes the fix a bit safer.

If anybody finds this discussion and wants a workaround without upgrading django-wiki to master, here is a monkeypatch I did:

`monkeypatch.py`:
    from wiki.plugins.links.mdx import urlize

    old_makeExtension = urlize.makeExtension
    if not hasattr(old_makeExtension, "monkey_patched"):

        def makeExtension(configs=None):
            if configs is None: configs = {}
            return old_makeExtension(configs)
        makeExtension.monkey_patched = True

        urlize.makeExtension = makeExtension

And then `import monkeypatch.py` from within (for lack of better idea) `settings.py`
