### ISSUE TITLE
Error creating new wiki

### ISSUE THREAD

**Issue by programacion-web** [django-wiki/django-wiki#408]
Hello friands,

I try to create a new wiki follow the instructions but I get the following error:

```
#python2.7 manage.py runserver 9999
/usr/local/lib/python2.7/site-packages/mptt/managers.py:36: RemovedInDjango18Warning: `TreeManager.get_query_set` method should be renamed `get_queryset`.
  class TreeManager(models.Manager):

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/wiki/models/__init__.py", line 47, in <module>
    'django-wiki: needs django.core.context_processors.request in TEMPLATE_CONTEXT_PROCESSORS')
django.core.exceptions.ImproperlyConfigured: django-wiki: needs django.core.context_processors.request in TEMPLATE_CONTEXT_PROCESSORS
```

In settings.py i add:

```
'django.contrib.sites', # django 1.6.2
'django.contrib.humanize',
'django_nyt',
'mptt',
'sekizai',
'sorl.thumbnail',
'wiki',
'wiki.plugins.attachments',
'wiki.plugins.notifications',
'wiki.plugins.images',
'wiki.plugins.macros',
```

I delete the following lines settings.py and works but without the wiki

```
'wiki',
'wiki.plugins.attachments',
'wiki.plugins.notifications',
'wiki.plugins.images',
'wiki.plugins.macros',
```

**Comment by benjaoming** [comment]
As the error states, it would be recommended to look at `TEMPLATE_CONTEXT_PROCESSORS` ?
