### ISSUE TITLE
'models not found' error

### ISSUE THREAD

**Issue by gkb** [django-wiki/django-wiki#437]
How do I work around this error?

````
Traceback (most recent call last):
  File "/home/vagrant/Code_Pen/python-wiki/pythonwiki/lib/python3.4/site-packages/django/template/loaders/app_directories.py", line 23, in <module>
    mod = import_module(app)
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 104, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/Code_Pen/python-wiki/pythonwiki/lib/python3.4/site-packages/django_notify/__init__.py", line 25, in <module>
    import models
ImportError: No module named 'models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/Code_Pen/python-wiki/pythonwiki/lib/python3.4/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/Code_Pen/python-wiki/pythonwiki/lib/python3.4/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/Code_Pen/python-wiki/pythonwiki/lib/python3.4/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/vagrant/Code_Pen/python-wiki/pythonwiki/lib/python3.4/site-packages/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 104, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2189, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/Code_Pen/python-wiki/pythonwiki/lib/python3.4/site-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/home/vagrant/Code_Pen/python-wiki/pythonwiki/lib/python3.4/site-packages/django/template/loaders/app_directories.py", line 25, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
````

**Comment by benjaoming** [comment]
You seem to be using an odd mix of Python 3.4 and South. And you have django_notify installed, remove it and use django_nyt

This is not a bug, and not a feature request... it's a support request.

When you click New Issue, there's this:

![screenshot from 2015-06-23 13 11 12](https://cloud.githubusercontent.com/assets/374612/8489897/02e32530-2121-11e5-8fe0-5dca4252cf79.png)
