### ISSUE TITLE
TypeError: render_to_response() got an unexpected keyword argument 'context_instance'

### ISSUE THREAD

**Issue by jedie** [django-wiki/django-wiki#583]
I installed the git version and get this:
```
Internal Server Error: /_revision/merge/14/89/preview/
Traceback (most recent call last):
  File "/home/jens/django_wiki_venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/jens/django_wiki_venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/jens/django_wiki_venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jens/django_wiki_venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jens/django_wiki_venv/src/django-wiki/testproject/wiki/decorators.py", line 177, in wrapper
    return func(request, article, *args, **kwargs)
  File "/home/jens/django_wiki_venv/src/django-wiki/testproject/wiki/views/article.py", line 878, in merge
    return render_to_response(template_file, context_instance=c)
TypeError: render_to_response() got an unexpected keyword argument 'context_instance'
```

I just installed by:
```
pip install Pillow -e git+git://github.com/django-wiki/django-wiki.git#egg=django-wiki
```

and get this:
```
$ pip freeze
Django==1.10.3
django-classy-tags==0.8.0
django-mptt==0.8.6
django-nyt==1.0b1
django-sekizai==0.10.0
Markdown==2.6.7
Pillow==3.4.2
pkg-resources==0.0.0
six==1.10.0
sorl-thumbnail==12.3
-e git://github.com/django-wiki/django-wiki.git@6b2cb1a5b23e8c0ca83954cdc4c8dfb7ed6c8787#egg=wiki
```

**Comment by benjaoming** [comment]
Thanks for reporting this, seems to be an issue with Django 1.10.
