### ISSUE TITLE
ImportError: No module named plugins

### ISSUE THREAD

**Issue by enginefuture** [django-wiki/django-wiki#594]
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'django_nyt',
    'mptt',
    'sekizai',
    'sorl.thumbnail',
    'wiki',
    'wiki.plugins.attachments',
    'wiki.plugins.notifications',
    'wiki.plugins.images',
    'wiki.plugins.macros',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wiki.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                "sekizai.context_processors.sekizai",
            ],
        },
    },
]

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/tabshi/pysrc/2.7/djangowiki/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/tabshi/pysrc/2.7/djangowiki/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/tabshi/pysrc/2.7/djangowiki/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/tabshi/pysrc/2.7/djangowiki/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/tabshi/pysrc/2.7/djangowiki/lib/python2.7/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/Users/tabshi/.pyenv/versions/2.7.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named plugins

somebody help me ..

**Comment by benjaoming** [comment]
@enginefuture it's hard to tell from this, please ask on IRC or the mailing list.

**Comment by murtaghj** [comment]
I am trying to make this app work also and having issues with importing plugins. The issue occurs when doing the syncdb command; 

seeing the following error below;

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/wiki/Env/wikisite/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/wiki/Env/wikisite/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/wiki/Env/wikisite/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/wiki/Env/wikisite/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/wiki/Env/wikisite/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named plugins

Here is what I have installed;
bleach (1.5.0)
Django (1.10.7)
django-classy-tags (0.8.0)
django-mptt (0.8.7)
django-nyt (1.0b2)
django-sekizai (0.10.0)
gunicorn (19.7.1)
html5lib (0.9999999)
Markdown (2.6.8)
MySQL-python (1.2.5)
olefile (0.44)
Pillow (4.1.1)
pip (9.0.1)
pytz (2017.2)
setuptools (28.8.0)
six (1.10.0)
sorl-thumbnail (12.3)
uWSGI (2.0.15)
wheel (0.29.0)
wiki (0.2.4)


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'django_nyt',
    'mptt',
    'sekizai',
    'sorl.thumbnail',
    'wiki',
    'wiki.plugins.attachments',
    'wiki.plugins.notifications',
    'wiki.plugins.images',
    'wiki.plugins.macros',
]

Anybody got any ideas as to whats went wrong? 

Thanks

**Comment by benjaoming** [comment]
Sounds like `wiki` isn't a module that's available. Try opening `python`

```
>>> from wiki import plugins
```

Maybe for instance your virtualenv isn't activated.

**Comment by murtaghj** [comment]
Hi thanks for getting back. I am in the virtualenv but I cant import directly from python either.  See below;

(wikisite) [wiki@c3-dl380g9-90-vm04 wiki]$ python 
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> 
>>> from wiki import plugins
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name plugins
>>> 
>>> 
>>> 
>>> 
>>> import wiki 
>>> 
>>> 
>>> 
>>> 


Thanks

**Comment by benjaoming** [comment]
You have some other module called `wiki`. Try:

``` 
>>> import wiki
>>> print(wiki.__file__)
```

**Comment by murtaghj** [comment]
Your absolutly right Ben. It actually came to me after I posted my last comment. Changed the name of the other module and its all working great now. Great tool by the way. Thanks for the support.

**Comment by benjaoming** [comment]
Yes, another time remember to:

1) Don't open up issues of stuff that you already know has an issue
2) Read the guidelines, I wrote them to not have to spend time supporting stuff in Github issues (which are for development)

![screenshot from 2017-05-09 14-13-03](https://cloud.githubusercontent.com/assets/374612/25850222/ba49b058-34c1-11e7-85c3-4f554defae4c.png)

**Comment by shivanand199** [comment]
PS C:\DemoProject\WFMIS-master>  python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 338, in execute
    django.setup()
  File "C:\Python27\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Python27\lib\site-packages\django\apps\config.py", line 120, in create
    mod = import_module(mod_path)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named plugins

**Comment by shivanand199** [comment]
The issue occurs when doing the syncdb command
