### ISSUE TITLE
ImportError: No module named globalhistory

### ISSUE THREAD

**Issue by daicoolb** [django-wiki/django-wiki#685]
Traceback (most recent call last):
  File "/home/liujie/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/liujie/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/liujie/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/liujie/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/liujie/.local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/liujie/.local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/liujie/.local/lib/python2.7/site-packages/django/apps/config.py", line 127, in create
    import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named globalhistory

**Comment by benjaoming** [comment]
I would think you've mixed up the released version and the current `master` branch. The `globalhistory` plugin isn't released yet, remove it from `INSTALLED_APPS`
