### ISSUE TITLE
ImportError: No module named globalhistory

### ISSUE THREAD

**Issue by daicoolb** [django-wiki/django-wiki#695]
Traceback (most recent call last):
  File "/home/liujie/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/liujie/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/liujie/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/liujie/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/liujie/.local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/liujie/.local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/liujie/.local/lib/python2.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/home/liujie/miniconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named globalhistory

**Comment by teury** [comment]
I recommend using the stable version.

wiki 0.2 and django 1.10

**Comment by benjaoming** [comment]
@daicoolb you already posted this in https://github.com/django-wiki/django-wiki/issues/685 - please don't abuse people's time
