### ISSUE TITLE
Support Django 2.0

### ISSUE THREAD

**Issue by citxx** [django-wiki/django-wiki#784]
Django 2.0 release notes: https://docs.djangoproject.com/en/2.0/releases/2.0/

**Comment by citxx** [comment]
Currently I'm getting an error when running `manage.py runserver`:

```
Traceback (most recent call last):
  File "/home/citxx/programming/SIStema/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/citxx/programming/SIStema/venv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/citxx/programming/SIStema/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/citxx/programming/SIStema/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/home/citxx/programming/SIStema/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/citxx/programming/SIStema/venv/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/citxx/programming/SIStema/venv/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/citxx/programming/SIStema/venv/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/citxx/programming/SIStema/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/citxx/programming/SIStema/venv/lib/python3.5/site-packages/wiki/models/__init__.py", line 11, in <module>
    from .article import *  # noqa
  File "/home/citxx/programming/SIStema/venv/lib/python3.5/site-packages/wiki/models/article.py", line 7, in <module>
    from django.core.urlresolvers import reverse
ImportError: No module named 'django.core.urlresolvers'
```

From release notes:

> The `django.core.urlresolvers` module is removed in favor of its new location, `django.urls`

**Comment by benjaoming** [comment]
Have you seen #755 ?

**Comment by citxx** [comment]
Sorry, I tried to search, but haven't found it.

**Comment by citxx** [comment]
I see, it's because I searched issues, but not pull requests
