### ISSUE TITLE
URL Include Circular Reference Error

### ISSUE THREAD

**Issue by pstreck** [django-wiki/django-wiki#886]
I am currently running into an issue including wiki.urls in my project. I am running Windows 10 Professional, Python 3.6.2, Django 1.11.14. The error is as follows:

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001BD23F6DE1A>
Traceback (most recent call last):
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\urls\resolvers.py", line 408, in url_patterns
    iter(patterns)
TypeError: 'module' object is not iterable

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\utils\autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\core\management\base.py", line 360, in check
    include_deployment_checks=include_deployment_checks,
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\core\management\base.py", line 347, in _run_checks
    return checks.run_checks(**kwargs)
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\core\checks\registry.py", line 82, in run_checks
    new_errors = check(app_configs=app_configs)
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\core\checks\urls.py", line 17, in check_url_config
    return check_resolver(resolver)
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\core\checks\urls.py", line 27, in check_resolver
    return check_method()
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\urls\resolvers.py", line 256, in check
    warnings.extend(check_resolver(pattern))
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\core\checks\urls.py", line 27, in check_resolver
    return check_method()
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\urls\resolvers.py", line 255, in check
    for pattern in self.url_patterns:
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "Documents\Projects\Documentation\venv\lib\site-packages\django\urls\resolvers.py", line 415, in url_patterns
    raise ImproperlyConfigured(msg.format(name=self.urlconf_name))
django.core.exceptions.ImproperlyConfigured: The included URLconf '<module 'wiki.urls' from 'Documents\\Projects\\Documentation\\venv\\lib\\site-packages\\wiki\\urls.py'>' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import.`'
```
I have added the following to settings.py:

```
   INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django.contrib.sites.apps.SitesConfig',
        'django.contrib.humanize.apps.HumanizeConfig',
        'django_nyt.apps.DjangoNytConfig',
        'mptt',
        'sekizai',
        'sorl.thumbnail',
        'wiki.apps.WikiConfig',
        'wiki.plugins.attachments.apps.AttachmentsConfig',
        'wiki.plugins.notifications.apps.NotificationsConfig',
        'wiki.plugins.images.apps.ImagesConfig',
        'wiki.plugins.macros.apps.MacrosConfig',
    ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
            ],
        },
    },
]

WIKI_ACCOUNT_HANDLING = True
WIKI_ACCOUNT_SIGNUP_ALLOWED = True
LOGIN_REDIRECT_URL = reverse_lazy('wiki:get', kwargs={'path': ''})
```

urls.py is configured as follows:

```
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^notifications/', include('django_nyt.urls')),
    url(r'', include('wiki.urls'))
]
```

**Comment by benjaoming** [comment]
That's really strange, never seen this error before. Please do update if you have any more hints or debugging!

I'll try and reproduce when I have time.

**Comment by pstreck** [comment]
I wasn't able to solve this issue, but I did move to wiki 0.4a4 and Django 2.0 without a problem.

**Comment by benjaoming** [comment]
That is great to hear! I am trying to reproduce this issue, but I am getting confused about which original version of `django-wiki` you have produced this on.

I'm afraid that somehow the meta data on PyPi is playing tricks. See: https://github.com/pypa/pip/issues/5617

**Comment by benjaoming** [comment]
I tried reproducing this with no luck. Clean project + Django 1.11.14.

Sorry, need more input if this should be solved. All seems to work fine on Django 1.11 and 2.0 currently.

**Comment by pgdju** [comment]
Dear,
I found the same king of problem with `pip install wiki`. I solve the problem with the second possibility : `pip install git+git://github.com/django-wiki/django-wiki.git`.

The problem was that with the wiki/urls.py file is not the same. 
Espacially : 

```
urlpatterns = [
    url(r'^', sites.site.urls),
]
```
is missing.
