### ISSUE TITLE
Installation: Initial migrate fails

### ISSUE THREAD

**Issue by their** [django-wiki/django-wiki#929]
Following the guide from here: (https://django-wiki.readthedocs.io/en/latest/installation.html).

> $ uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

> $ virtualenv dwiki-venv && source dwiki-venv/bin/activate
(dwiki-venv) $ django-admin startproject django_wiki && cd django_wiki
(dwiki-venv) $ sudo pip install --pre wiki
(dwiki-venv) $ nano django_wiki/settings.py # Add list of installed apps from (https://django-wiki.readthedocs.io/en/latest/installation.html)
(dwiki-venv) $ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/wiki/models/__init__.py", line 5, in <module>
    from .article import *  # noqa
  File "/usr/local/lib/python2.7/dist-packages/wiki/models/article.py", line 91
    yield from obj.content_object.get_ancestors()
             ^
SyntaxError: invalid syntax

**Comment by benjaoming** [comment]
Neither this project nor Django 2.x supports Python 2.7
