### ISSUE TITLE
Error in 500.html or notifications settings

### ISSUE THREAD

**Issue by benjaoming** [django-wiki/django-wiki#977]
Reported by @atombrella - https://demo.django-wiki.org/_plugin/notifications/ gives a 502 bad gateway. This seems to likely be caused by the 500.html page not rendering.

Traceback:

```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endblocktrans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
    response = self.get_response(request)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 78, in get_response
    response = self._middleware_chain(request)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "./testproject/views.py", line 11, in server_error
    t = loader.get_template(template_name)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/loaders/cached.py", line 54, in get_template
    template = super().get_template(template_name, skip)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 16: 'endblocktrans', expected 'endblock'. Did you forget to register or load this tag?
[pid: 15832|app: 0|req: 1/2] 78.70.183.70 () {48 vars in 870 bytes} [Mon Oct  7 14:32:02 2019] GET /_plugin/notifications/ => generated 0 bytes in 183 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

**Comment by benjaoming** [comment]
I can't reproduce this. But we're adding automated tests to this page in #979
